/**
 * ZATCA PKCS#10 Certificate Signing Request (M12.3).
 *
 * Structure is DECLARED with `@peculiar/asn1-*` and DER-encoded by the library;
 * we never hand-write ASN.1. Signing uses `node:crypto` because WebCrypto has no
 * secp256k1 (see `keys.ts`).
 *
 * ── 🔴 THE REAL STRUCTURE — verified by decoding a CSR from `fatoora -csr` ──
 * The spec's Table 1 reads as though every field is a subject-DN attribute.
 * **It is not.** Parsing a CSR generated by ZATCA's own SDK from their own
 * example config shows:
 *
 *   SUBJECT DN — only FOUR attributes:
 *       C, OU, O, CN
 *
 *   subjectAltName (2.5.29.17) → dirName — EVERYTHING ELSE, in this order:
 *       2.5.4.4  surname           → EGS serial "1-<Mfr>|2-<Model>|3-<Serial>"
 *       0.9.2342.19200300.100.1.1 UID → 15-digit VAT number
 *       2.5.4.12 title             → INVOICE TYPE ("1100")
 *       2.5.4.26 registeredAddress → location
 *       2.5.4.15 businessCategory  → INDUSTRY
 *
 *   PLUS a required certificate-template extension (1.3.6.1.4.1.311.20.2).
 *
 * Three traps in one structure, each producing a rejected CSR at M12.4 with no
 * useful diagnostic:
 *   1. Invoice type is `title` (2.5.4.12), NOT `businessCategory` (2.5.4.15) —
 *      the spec assigns 2.5.4.15 to *two* different rows.
 *   2. The EGS serial uses **2.5.4.4 (surname)**, not 2.5.4.5 (serialNumber),
 *      despite the spec calling it a "serial number".
 *   3. `title` / `registeredAddress` / `businessCategory` live in the SAN
 *      dirName, not the subject DN.
 */
import { AsnConvert, OctetString } from "@peculiar/asn1-schema";
import {
  AlgorithmIdentifier,
  Attribute,
  AttributeTypeAndValue,
  AttributeValue,
  Extension,
  Extensions,
  GeneralName,
  Name,
  RelativeDistinguishedName,
  SubjectAlternativeName,
  SubjectPublicKeyInfo,
} from "@peculiar/asn1-x509";
import { Attributes, CertificationRequest, CertificationRequestInfo } from "@peculiar/asn1-csr";
import { createSign, type KeyObject } from "crypto";
import { assertZatcaCurve } from "./keys";

const OID = {
  commonName: "2.5.4.3",
  /** The EGS serial goes here — surname, NOT serialNumber (2.5.4.5). */
  surname: "2.5.4.4",
  country: "2.5.4.6",
  organization: "2.5.4.10",
  organizationalUnit: "2.5.4.11",
  /** INVOICE TYPE. Not businessCategory. */
  title: "2.5.4.12",
  /** INDUSTRY. Not the invoice type. */
  businessCategory: "2.5.4.15",
  registeredAddress: "2.5.4.26",
  /** The 15-digit VAT number, in the SAN dirName. */
  uid: "0.9.2342.19200300.100.1.1",
  extensionRequest: "1.2.840.113549.1.9.14",
  subjectAltName: "2.5.29.17",
  /** Microsoft certificate-template-name extension, required by ZATCA's CA. */
  certificateTemplateName: "1.3.6.1.4.1.311.20.2",
  ecdsaWithSHA256: "1.2.840.10045.4.3.2",
} as const;

/**
 * The certificate template name. ZATCA's CA rejects a CSR carrying the wrong one
 * for the environment — `-nonprod` on their CLI is exactly this switch.
 */
export const CERT_TEMPLATE = {
  production: "ZATCA-Code-Signing",
  /** Sandbox AND simulation both use the TST template. */
  nonProduction: "TSTZATCA-Code-Signing",
} as const;

export interface ZatcaCsrInput {
  /** Solution unit name / asset tracking number. */
  commonName: string;
  /** Taxpayer name. */
  organizationName: string;
  /** Branch name, or the 10-digit TIN for a VAT group member. */
  organizationalUnitName: string;
  /** ISO 3166 alpha-2. */
  countryName: string;
  /** 4-digit TSCZ flags, e.g. "1100" = standard + simplified. → SAN `title`. */
  invoiceType: string;
  /** Branch / device location. → SAN `registeredAddress`. */
  locationAddress: string;
  /** Industry or sector. → SAN `businessCategory`. */
  industryBusinessCategory: string;
  /** 15-digit VAT registration number. → SAN `UID`. */
  organizationIdentifier: string;
  /** `1-<Manufacturer>|2-<Model>|3-<Serial>`. → SAN `surname`. */
  egsSerialNumber: string;
  /** false ⇒ the TST template, for sandbox and simulation. */
  production: boolean;
}

function rdn(type: string, value: string): RelativeDistinguishedName {
  return new RelativeDistinguishedName([
    new AttributeTypeAndValue({ type, value: new AttributeValue({ utf8String: value }) }),
  ]);
}

/** Subject DN — four attributes only. Everything else is in the SAN. */
function buildSubject(input: ZatcaCsrInput): Name {
  return new Name([
    rdn(OID.country, input.countryName),
    rdn(OID.organizationalUnit, input.organizationalUnitName),
    rdn(OID.organization, input.organizationName),
    rdn(OID.commonName, input.commonName),
  ]);
}

/** SAN dirName, in ZATCA's own field order. */
function buildSubjectAltName(input: ZatcaCsrInput): Extension {
  const dirName = new Name([
    rdn(OID.surname, input.egsSerialNumber),
    rdn(OID.uid, input.organizationIdentifier),
    rdn(OID.title, input.invoiceType),
    rdn(OID.registeredAddress, input.locationAddress),
    rdn(OID.businessCategory, input.industryBusinessCategory),
  ]);
  const san = new SubjectAlternativeName([new GeneralName({ directoryName: dirName })]);
  return new Extension({
    extnID: OID.subjectAltName,
    critical: false,
    extnValue: new OctetString(AsnConvert.serialize(san)),
  });
}

/** The template-name extension: a bare DER UTF8String. */
function buildTemplateExtension(production: boolean): Extension {
  const name = production ? CERT_TEMPLATE.production : CERT_TEMPLATE.nonProduction;
  const bytes = Buffer.from(name, "utf8");
  const der = Buffer.concat([Buffer.from([0x0c, bytes.length]), bytes]);
  return new Extension({
    extnID: OID.certificateTemplateName,
    critical: false,
    extnValue: new OctetString(der),
  });
}

/**
 * Build and sign a PKCS#10 CSR. The request is signed with the private key as
 * proof-of-possession (spec Req 7).
 */
export function buildZatcaCsr(
  input: ZatcaCsrInput,
  privateKey: KeyObject,
  publicKey: KeyObject,
): string {
  assertZatcaCurve(privateKey);

  const spkiDer = publicKey.export({ type: "spki", format: "der" }) as Buffer;

  const info = new CertificationRequestInfo({
    version: 0,
    subject: buildSubject(input),
    subjectPKInfo: AsnConvert.parse(spkiDer, SubjectPublicKeyInfo),
    attributes: new Attributes([
      new Attribute({
        type: OID.extensionRequest,
        values: [
          AsnConvert.serialize(
            new Extensions([buildTemplateExtension(input.production), buildSubjectAltName(input)]),
          ),
        ],
      }),
    ]),
  });

  const infoDer = Buffer.from(AsnConvert.serialize(info));
  // node:crypto emits a DER-encoded ECDSA signature, which is what X.509 wants.
  const signature = createSign("sha256").update(infoDer).sign(privateKey);

  const request = new CertificationRequest({
    certificationRequestInfo: info,
    signatureAlgorithm: new AlgorithmIdentifier({ algorithm: OID.ecdsaWithSHA256 }),
    // The ASN.1 schema wants a plain ArrayBuffer, not a Node Buffer view.
    signature: signature.buffer.slice(
      signature.byteOffset,
      signature.byteOffset + signature.byteLength,
    ) as ArrayBuffer,
  });

  return toPem(Buffer.from(AsnConvert.serialize(request)), "CERTIFICATE REQUEST");
}

function toPem(der: Buffer, label: string): string {
  const b64 = der.toString("base64").replace(/(.{64})/g, "$1\n");
  return `-----BEGIN ${label}-----\n${b64}${b64.endsWith("\n") ? "" : "\n"}-----END ${label}-----\n`;
}
