-- L1 (2026-09-03): the sentinel default dies with the form field that now
-- writes real Arabic (the tax_category_code incident one column over: a NOT
-- NULL default no form ever set). NULL is the honest absence; the Arabic PDF
-- falls back to the English description. Existing sentinel rows convert —
-- they are the DEFAULT talking, not a user's words. (Generated by drizzle-kit
-- now that T1 is closed; the UPDATE is the hand-added data half.)
ALTER TABLE "invoice_items" ALTER COLUMN "description_ar" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "invoice_items" ALTER COLUMN "description_ar" DROP NOT NULL;--> statement-breakpoint
UPDATE "invoice_items" SET "description_ar" = NULL WHERE "description_ar" = '(not yet translated)';
