-- The sentinel-default FAMILY dies (the L1/0067 treatment, applied to the 8
-- remaining tables the schema comment named): NULL is the honest absence, and
-- nothing has to RECOGNISE a magic string to know a translation is missing.
-- Existing sentinel rows convert — they are the DEFAULT talking, not a user's
-- words — and so do empty strings, the same stand-in typed by a form instead
-- of a migration. (ALTERs generated by drizzle-kit; the UPDATEs are the
-- hand-added data half, per 0067.)
ALTER TABLE "customers" ALTER COLUMN "name_ar" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "customers" ALTER COLUMN "name_ar" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "vendors" ALTER COLUMN "name_ar" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "vendors" ALTER COLUMN "name_ar" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "name_ar" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "name_ar" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "quotation_items" ALTER COLUMN "description_ar" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "quotation_items" ALTER COLUMN "description_ar" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "purchase_order_items" ALTER COLUMN "description_ar" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "purchase_order_items" ALTER COLUMN "description_ar" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "name_ar" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "name_ar" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "job_title_ar" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "job_title_ar" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "fixed_assets" ALTER COLUMN "name_ar" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "fixed_assets" ALTER COLUMN "name_ar" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "budgets" ALTER COLUMN "name_ar" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "budgets" ALTER COLUMN "name_ar" DROP NOT NULL;;--> statement-breakpoint
UPDATE "customers" SET "name_ar" = NULL WHERE "name_ar" IN ('(not yet translated)', '');--> statement-breakpoint
UPDATE "vendors" SET "name_ar" = NULL WHERE "name_ar" IN ('(not yet translated)', '');--> statement-breakpoint
UPDATE "products" SET "name_ar" = NULL WHERE "name_ar" IN ('(not yet translated)', '');--> statement-breakpoint
UPDATE "quotation_items" SET "description_ar" = NULL WHERE "description_ar" IN ('(not yet translated)', '');--> statement-breakpoint
UPDATE "purchase_order_items" SET "description_ar" = NULL WHERE "description_ar" IN ('(not yet translated)', '');--> statement-breakpoint
UPDATE "employees" SET "name_ar" = NULL WHERE "name_ar" IN ('(not yet translated)', '');--> statement-breakpoint
UPDATE "employees" SET "job_title_ar" = NULL WHERE "job_title_ar" IN ('(not yet translated)', '');--> statement-breakpoint
UPDATE "fixed_assets" SET "name_ar" = NULL WHERE "name_ar" IN ('(not yet translated)', '');--> statement-breakpoint
UPDATE "budgets" SET "name_ar" = NULL WHERE "name_ar" IN ('(not yet translated)', '');
