import { pgTable, text, timestamp, integer, uuid, index, jsonb } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { organizationsTable } from "./organizations";
import { companiesTable } from "./companies";
import { billsTable } from "./bills";

/**
 * A captured supplier document — photograph, extraction, and provenance (A1).
 *
 * ── 🔴 THE LIFECYCLE IS STAGE → PROMOTE, AND THAT IS THE DESIGN ────────────
 * Outbound e-invoices go straight into `ArchiveStore`, which has **no delete
 * method by design** (ZATCA §5.5: a generated invoice must never be deleted or
 * altered). Inbound captures cannot simply inherit that, for three reasons:
 *
 *  1. **They may be wrong.** An outbound invoice is generated by us and correct
 *     by construction. A capture is whatever the user pointed a phone at — a
 *     blurry frame, the wrong receipt, a duplicate.
 *  2. **Most are evidence of nothing.** Every archive row corresponds to an
 *     issued invoice; captures include abandoned attempts. Retaining a discarded
 *     photo for six years is cost and liability with no compliance benefit.
 *  3. **🔴 Personal data.** A surface accepting phone photographs will
 *     eventually receive an ID card on the desk or a face in frame. "Immutable
 *     by design" is defensible for an invoice WE issued; it is not obviously
 *     defensible for an accidental photograph of a third party. See queue item
 *     **C8 (PDPL)** — unresolved, and it may CONFLICT with C7's retention
 *     requirement.
 *
 * So a capture is **staged** in deletable storage, and **promoted** into the
 * immutable archive at the moment it becomes evidence: **when it is posted to a
 * bill.** Abandoned captures are purged. `ArchiveStore`'s guarantee stays
 * absolute where it matters and does not reach every stray photograph.
 *
 * ── 🔴 PROMOTION IS AN OUTBOX, NOT A TRANSACTION ───────────────────────────
 * Object storage is not transactional with Postgres, so "atomic with the bill
 * posting" cannot mean a two-phase commit. It means the same pattern M12.6
 * already uses for ZATCA: **the INTENT commits in the bill's transaction**
 * (`bill_id`, `retain_until`, `status = 'promotion_pending'`), and a job moves
 * the bytes afterwards, idempotently.
 *
 * That makes both wrong states impossible or visible:
 *   - *evidence for a bill that does not exist* — impossible: the link is
 *     written inside the bill's own transaction and rolls back with it;
 *   - *a bill whose evidence never promoted* — visible as `promotion_pending`,
 *     retried by the job, and surfaceable rather than silent.
 */
export const capturedDocumentsTable = pgTable(
  "captured_documents",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id")
      .notNull()
      .default(sql`(nullif(current_setting('app.current_org_id', true), ''))::uuid`)
      .references(() => organizationsTable.id),
    companyId: uuid("company_id")
      .notNull()
      .default(sql`(nullif(current_setting('app.current_company_id', true), ''))::uuid`)
      .references(() => companiesTable.id),

    /**
     * `staged`             — in deletable staging storage, not yet evidence.
     * `promotion_pending`  — posted to a bill; bytes still to move. Committed
     *                        with the bill, so this state is durable.
     * `promoted`           — in the immutable archive. Retention applies.
     * `discarded`          — user abandoned it; the purge job may delete it.
     */
    status: text("status").notNull().default("staged"),

    // ── the document ────────────────────────────────────────────────────────
    /** Path in STAGING storage. Cleared once promoted and the staged copy is gone. */
    stagingPath: text("staging_path"),
    /** Path in the immutable archive. Set on promotion. */
    archivePath: text("archive_path"),
    contentType: text("content_type").notNull(),
    byteSize: integer("byte_size").notNull(),
    sha256: text("sha256").notNull(),

    // ── provenance: the actual A1 requirement ───────────────────────────────
    /**
     * 🔴 `qr` | `ocr` | `manual`.
     *
     * The question a disputed figure raises is **"was this decoded, read by OCR,
     * or typed?"** — and until A1 nothing recorded it. A QR decode is exact
     * because the supplier's own system wrote those bytes; OCR is a guess from
     * pixels. The distinction changes how much the figure should be trusted.
     */
    source: text("source").notNull(),
    /** Per-field source, so provenance survives the user editing one field. */
    fieldSources: jsonb("field_sources"),
    /** The extraction as captured, before any human edit. */
    extraction: jsonb("extraction"),

    // ── ZATCA QR ────────────────────────────────────────────────────────────
    /** Raw TLV payload, when one was read. Kept for re-verification. */
    qrPayload: text("qr_payload"),
    /**
     * `unsigned` — no Phase 2 tags, nothing to verify (Phase 1 QR).
     * `verified` — the signature checks out: this invoice is genuine.
     * `failed`   — 🔴 tags present but the signature does NOT verify.
     * `error`    — verification could not be completed.
     *
     * Decided SERVER-SIDE. A client-side verdict can be faked, and the claim is
     * about whether the customer's input-VAT deduction survives ZATCA.
     */
    signatureStatus: text("signature_status"),
    signatureDetail: text("signature_detail"),

    // ── linkage + retention ─────────────────────────────────────────────────
    /** Set inside the bill's transaction — this is what makes the link atomic. */
    billId: integer("bill_id").references(() => billsTable.id),
    /**
     * Conservative default (queue C7): inbound documents are retained to the
     * same standard as outbound, because a supplier invoice is the evidence for
     * an input-VAT deduction. NOT a settled reading of the obligation — see C7
     * and C8, which must be answered together.
     */
    retainUntil: timestamp("retain_until", { withTimezone: true }),

    capturedBy: integer("captured_by"),
    capturedAt: timestamp("captured_at", { withTimezone: true }).notNull().defaultNow(),
    promotedAt: timestamp("promoted_at", { withTimezone: true }),
    discardedAt: timestamp("discarded_at", { withTimezone: true }),
  },
  (table) => [
    index("captured_documents_org_status_idx").on(table.organizationId, table.status),
    index("captured_documents_bill_idx").on(table.billId),
    // The purge job's query: staged/discarded captures older than the window.
    index("captured_documents_captured_at_idx").on(table.status, table.capturedAt),
  ],
);

export type CapturedDocument = typeof capturedDocumentsTable.$inferSelect;
export type InsertCapturedDocument = typeof capturedDocumentsTable.$inferInsert;
